# Generated by Django 2.0.5 on 2018-11-30 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PayInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('profile', models.CharField(max_length=200, verbose_name='简介')),
                ('price', models.FloatField(verbose_name='价格')),
                ('path', models.FilePathField(verbose_name='路径')),
            ],
        ),
    ]
