# Generated by Django 2.0.5 on 2018-11-30 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payinfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payinfo',
            name='path',
            field=models.FilePathField(path='/media/', verbose_name='路径'),
        ),
    ]
