# Generated by Django 2.0.5 on 2018-11-30 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payinfo', '0003_auto_20181130_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payinfo',
            name='path',
            field=models.FilePathField(verbose_name='路径'),
        ),
    ]
