# Generated by Django 2.0.5 on 2018-11-21 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsCategorty',
        ),
    ]
